### ISSUE TITLE
New feature normalization functionality on previous Elasticsearch versions (especially 7.3.2)

### ISSUE THREAD

**Issue by arthurbv2** [o19s/elasticsearch-learning-to-rank#312]
Hello,

I hope you guys are doing well.

Any chances to have the new feature normalization functionality in the pre-built list for the Elasticsearch versions prior to the 7.7.0?

It'd be really helpful to have this in the 7.3.2.

Thank you!

**Comment by nathancday** [comment]
Hey, thanks to the kind wishes, hope you are staying healthy too.

In the past we haven't gone backwards with features to support older versions, because of how fast new versions come out. But we do keep a branch for each Minor version and have one for [`es_7_3`](https://github.com/o19s/elasticsearch-learning-to-rank/tree/es_7_3), in case people want to develop on that. (e.g. cherry-pick the [feature norm commit] onto that branch and build a custom version).

**Comment by arthurbv2** [comment]
Thank you, @nathancday .

I tried to do this, however I've got this error.

![image](https://user-images.githubusercontent.com/49131627/84388266-a77dbb80-abca-11ea-9de5-d40032856d11.png)

**Comment by arthurbv2** [comment]
I also tried to build with gradle6.5 as it is done in the `master` of the project, but it seems to have some problem with the `RankMyFace`.

Do you know how to address some of these issues?


![image](https://user-images.githubusercontent.com/49131627/84388429-f6c3ec00-abca-11ea-8c02-37c77bd1ceb2.png)

**Comment by arthurbv2** [comment]
I am using `JDK14`.

**Comment by nathancday** [comment]
Cool. there's a lot of layers there. Let me try to build/install for 7.3.2 and I'll get back.

**Comment by arthurbv2** [comment]
Thanks in advance, @nathancday , it'd be really helpful.

I've got some advances in this, but still didnt have success in building the plugin with the feature nomalization for the Elasticsearch 7.3.2.

What I'm trying to do its to get some code classes from the Elasticsearch 7.7 repo to the ltr-plugin dir, because it seems to be some dependencies in there.

I feel like I've advanced, but still not got there.

**Comment by arthurbv2** [comment]
@nathancday ,

I've come to this:

/home/arthurcbv/Documents/LTR-Pugin/plugin/elasticsearch-learning-to-rank/src/main/java/com/o19s/es/ltr/feature/store/ObjectParser.java:69: error: incompatible types: Function<Context,Value> cannot be converted to Supplier<Value>
        return new ObjectParser<Value, Context>(name, valueBuilder);
                                                      ^
  where Context,Value are type-variables:
    Context extends Object declared in method <Value,Context>fromBuilder(String,Function<Context,Value>)
    Value extends Object declared in method <Value,Context>fromBuilder(String,Function<Context,Value>)

_____________________________________________________________________________
This is the MinMaxFeatureNormDefinition interaction with ObjectParser

    static {
        PARSER = ObjectParser.fromBuilder("min_max", MinMaxFeatureNormDefinition::new);
        PARSER.declareFloat(MinMaxFeatureNormDefinition::setMinimum, MINIMUM);
        PARSER.declareFloat(MinMaxFeatureNormDefinition::setMaximum, MAXIMUM);
    }
 
_______________________________________________________________________________

This is part of my ObjecParser:

public final class ObjectParser<Value, Context> extends AbstractObjectParser<Value, Context> {
    /**
     * Adapts an array (or varags) setter into a list setter.
     */
    public static <Value, ElementValue> BiConsumer<Value, List<ElementValue>> fromList(Class<ElementValue> c,
            BiConsumer<Value, ElementValue[]> consumer) {
        return (Value v, List<ElementValue> l) -> {
            @SuppressWarnings("unchecked")
            ElementValue[] array = (ElementValue[]) Array.newInstance(c, l.size());
            consumer.accept(v, l.toArray(array));
        };
    }
    
    public static <Value, Context> ObjectParser<Value, Context> fromBuilder(String name, Function<Context, Value> valueBuilder) {
        requireNonNull(valueBuilder, "Use the single argument ctor instead");
        return new ObjectParser<Value, Context>(name, valueBuilder);
    }

**Comment by nathancday** [comment]
Damn, you made a lot of progress! Sorry it's ending in a roadblock for now. I'll let you know how my end goes, hopefully early next week.

**Comment by arthurbv2** [comment]
Cool, @nathancday !

Been trying to have progress. 

It seems that I finally got the plugin built.

Yet, this is happening when I try to initialize the ltrstore.

![image](https://user-images.githubusercontent.com/49131627/84697108-f6f21d80-af23-11ea-9658-14f769ecb024.png)

**Comment by arthurbv2** [comment]
When I run `_cat/plugins/`, I can see the plugin installed.

**Comment by nathancday** [comment]
Looks like you've done the heavy lifting getting it to build. Do you have this published on a branch somewhere? 

In poking around this morning I was able to follow back to the `ObjectParser.fromBuilder` "can't find symbol" error and that looks like something Elastic changed [5 months ago](https://github.com/elastic/elasticsearch/blame/master/libs/x-content/src/main/java/org/elasticsearch/common/xcontent/ObjectParser.java#L179).

**Comment by arthurbv2** [comment]
I am not able to push it to a branch to this repo. Do not have permission. Guess I should have created a fork on this. I'll do that, and I'll tell you.

Yeah, what I did with this Elasticsearch dependencies was to get their code on their repo and copy into the features store folder.

It seems to be working now.

Latety, I've got problems on some unit tests, but in the sense that I was only concerned on getting the plugin build, I removed the 5 unit tests that were not passing.

Plus, I had a integration test error, but at this point, the plugin was already built, so I am able now to try it.

I've already solved the problem on installing the ltr store. I was pointing to a different Elasticsearch instances. It happens to the best families... haha

**Comment by arthurbv2** [comment]
My current status is: yesterday, I was able to publish a model to Elasticsearch with the feature_normalizers.

Today I'll make some tests on it.

But something seems to be strange in the plugin documentation:

I could'nt get this straight following the docs. 

First, it seems that `feature_normalizers` goes on the same level than definition. Or, at least, it was how I was able to publish the model in the Elasticsearch. The way that it is on the docs, I was getting an error.

Second, where that is the min-max example, there should be `min_max` instead of `standard`, right? 

![image](https://user-images.githubusercontent.com/49131627/84775299-6bc16800-afb5-11ea-9c95-a1728370876f.png)

**Comment by nathancday** [comment]
Lovely! That makes sense bringing in the Elastic code, I'm happy you were able to get it built up. I think your Java dev skills are better than mine!

This rapid changes to the Elastic code base is the main reason we don't attempt to back-port features. If you have what you need now I would keep it as a stable fork in your own repo. Merging things like this back to the version branch is sticky (i.e. what happens when someone upgrades from 7.3 to 7.4 and the feature norm isn't there anymore).

That's a good point you just raised about the docs. I'll double check today.
